WonderBox/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WonderBox.Models
{
    public class Users
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string UserID { get; set; }
        public decimal AmountOwed { get; set; }
        public int MonthlySubscription { get; set; }
        public int YearlySubscription { get; set; }
        public int TotalMonthlySubcription { get; set; }
        public int TotalYearlySubscription { get; set; }
        public int TotalMale { get; set; }
        public int TotalFemale { get; set; }
        public int TotalRegistered { get; set; }
        public decimal TotalMonthlyRevenuIncoming { get; set; }
    }
}

WonderBox/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WonderBox.Models;

namespace WonderBox.Controllers
{
    public class SurveysController : Controller
    {
        private MasterBoxDBContext db = new MasterBoxDBContext();
        Random GiftChances = new Random();
        People people = new People();

        public int Answer1;
        public int Answer2;
        public int Answer3;
        public int Answer4;
        public int Answer5;
        public int Answer6;
        public string SumOfAnswers;
        public List<Item> ListOfGifts;


        // GET: Surveys
        public ActionResult Index()
        {
            return View(db.Surveys.ToList());
        }

        public ActionResult ProfileView()
        {
            return View(db.People);
        }

        // GET: Surveys/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            return View(survey);
        }

        // GET: Surveys/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Surveys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Quetion1,Quetion2,Quetion3,Quetion4,Quetion5,Quetion6")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                db.Surveys.Add(survey);
                db.SaveChanges();
                MatchSubscription(survey.ID);
                BoxAlgorithm();
                ItemSixToBox();
                ItemOneToBox();
                ItemTwoToBox();
                ItemThreeToBox();
                ItemForthToBox();
                ItemFifthToBox();
                return RedirectToAction("Index");

            }

            return View(survey);
        }

        // GET: Surveys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            return View(survey);
        }

        // POST: Surveys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Quetion1,Quetion2,Quetion3,Quetion4,Quetion5,Quetion6")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                db.Entry(survey).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(survey);
        }

        // GET: Surveys/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            return View(survey);
        }

        // POST: Surveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Survey survey = db.Surveys.Find(id);
            db.Surveys.Remove(survey);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void MatchSubscription(int id)
        {
            Survey survey = db.Surveys.Find(id);
            this.Answer1 = Int32.Parse(survey.Quetion1);
            this.Answer2 = Int32.Parse(survey.Quetion2);
            this.Answer3 = Int32.Parse(survey.Quetion3);
            this.Answer4 = Int32.Parse(survey.Quetion4);
            this.Answer5 = Int32.Parse(survey.Quetion5);
            this.Answer6 = Int32.Parse(survey.Quetion6);

        }

        public void BoxAlgorithm()
        {
            int sum = this.Answer1 + this.Answer2 + this.Answer3 + this.Answer4 + this.Answer5 + Answer6;
            this.SumOfAnswers = sum.ToString();
        }

        public void decrementItemsFromDB(string paramString)
        {
            string stringToCompare = paramString;
            var query = db.Items.Where(ru => ru.Name == stringToCompare).Single();
            int GGQuantitiy = query.Quantity;
            query.Quantity--;
            db.SaveChanges();
        }


        public void ItemSixToBox()
        {
            char sixthItem = this.SumOfAnswers[0];
            if (sixthItem == '3')
            {
                decrementItemsFromDB("Fireball");

            }
            else if (sixthItem == '4')
            {
                decrementItemsFromDB("Gray Goose");
            }
            else if (sixthItem == '5')
            {
                decrementItemsFromDB("Everclear");
            }
        }

        public void ItemOneToBox()
        {
            char firstItem = this.SumOfAnswers[1];
            if (firstItem == '1')
            {
                int randomInt = GiftChances.Next(0, 100);
                if (randomInt >= 50)
                {
                    decrementItemsFromDB("Olive Garden Gift Card");
                }
                else
                {
                    decrementItemsFromDB("Texas Roadhouse Gift Card");
                }
            }
            else if (firstItem == '2')
            {
                decrementItemsFromDB("Starbucks Gift Card");
            }
        }

        public void ItemTwoToBox()
        {
            char secoundItem = this.SumOfAnswers[2];
            if (secoundItem == '5')
            {
                int randomInt = GiftChances.Next(0, 100);
                if (randomInt >= 50)
                {
                    decrementItemsFromDB("PredAlien - ActionFigure");
                }
                else
                {
                    decrementItemsFromDB("The Marionette - ActionFigure");
                }
            }
            else if (secoundItem == '4')
            {
                {
                    int randomInt = GiftChances.Next(0, 100);
                    if (randomInt >= 50)
                    {
                        decrementItemsFromDB("The Notebook - Blu-ray");
                    }
                    else
                    {
                        decrementItemsFromDB("Requiem for a Dream - Blu-ray");
                    }
                }
            }
        }

        public void ItemThreeToBox()
        {
            char thirdItem = this.SumOfAnswers[3];
            if (thirdItem == '9')
            {
                decrementItemsFromDB("Skrillex - Bangarang");
                decrementItemsFromDB("The Living Tombstone");
            }
            else if (thirdItem == '7')
            {
                decrementItemsFromDB("Linkin Park - Meteora");
            }
            else if (thirdItem == '5')
            {
                decrementItemsFromDB("Apocolptica - Cult");
            }
            else if (thirdItem == '3')
            {
                decrementItemsFromDB("Parov Stelar - Coco");
            }
        }

        public void ItemForthToBox()
        {
            char forthItem = SumOfAnswers[4];
            if (forthItem == '8')
            {
                decrementItemsFromDB("PlayStation Plus Membership");
            }
            else if (forthItem == '6')
            {
                decrementItemsFromDB("Xbox Live Membership");
            }
            else if (forthItem == '4')
            {
                decrementItemsFromDB("Steam Gift Card");
            }
        }

        public void ItemFifthToBox()
        {
            char fifthItem = SumOfAnswers[5];
            if (fifthItem == '6')
            {
                decrementItemsFromDB("Flash - Season 1");
            }

            else if (fifthItem == '5')
            {
                decrementItemsFromDB("Venom - Hoodie");
            }
        }
    }
}

WonderBox/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WonderBox.CustomFilters;
using WonderBox.Models;
using Microsoft.AspNet.Identity;


namespace WonderBox.Controllers
{
    public class UsersController : Controller
    {
        private MasterBoxDBContext db = new MasterBoxDBContext();

        // GET: Users
        public ActionResult Index()
        {
            var UserID = User.Identity.GetUserId();
            var UserInfo = db.Users.Where(userid => userid.UserID == UserID);
            return View(UserInfo.ToList());
        }

        [AuthLog(Roles = "Admin")]
        public ActionResult AdminView()
        {
            //var UserID = User.Identity.GetUserId();
            //var UserInfo = db.Users.Where(userid => userid.UserID == UserID).Single();

            //UserInfo.TotalMonthlySubcription = db.Users.Count();

            //var UserID = User.Identity.GetUserId();
            //var UserInfo = db.Users.Where(userid => userid.UserID == UserID).Single();

            //var Male = "Male";
            //var Female = "Female";

            //var MaleInfo = db.Users.Where(m => m.Gender == Male).Count();
            //var FemaleInfo = db.Users.Where(f => f.Gender == Female).Count();


            //UserInfo.TotalMale = MaleInfo;
            //UserInfo.TotalFemale = FemaleInfo;
                     

            return View(db.Users.ToList());
        }

        public ActionResult BuyMonthly()
        {
            var SubsName = "Mystery Box";
            var SubscriptionName = db.Subcriptions.Where(sub => sub.SubName == SubsName).Single();

            var UserID = User.Identity.GetUserId();
            var UserInfo = db.Users.Where(userid => userid.UserID == UserID).Single();

            UserInfo.AmountOwed += SubscriptionName.MonthlyPrice;
            UserInfo.MonthlySubscription++;
            UserInfo.TotalMonthlyRevenuIncoming += SubscriptionName.MonthlyPrice;
            
            db.SaveChanges();
            return View();
        }

        [AuthLog(Roles = "User")]
        public ActionResult BuyYearly()
        {
            var SubsName = "Mystery Box";
            var SubscriptionName = db.Subcriptions.Where(sub => sub.SubName == SubsName).Single();

            var UserID = User.Identity.GetUserId();
            var UserInfo = db.Users.Where(userid => userid.UserID == UserID).Single();

            UserInfo.AmountOwed += SubscriptionName.YearlyPrice;
            UserInfo.YearlySubscription++;
            UserInfo.TotalMonthlyRevenuIncoming += SubscriptionName.YearlyPrice / 12;
     
            db.SaveChanges();
            return View();
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address,City,State,Zipcode,Age,Gender")] Users users)
        {
            //var UserID = User.Identity.GetUserId();
            //var UserInfo = db.Users.Where(userid => userid.UserID == UserID).Single();

            if (ModelState.IsValid)
            {
                users.TotalRegistered++;
                users.UserID = User.Identity.GetUserId();
                db.Users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,City,State,Zipcode,Age,Gender")] Users users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Users users = db.Users.Find(id);
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WonderBox/Views/Users/AdminView.cshtml
@model IEnumerable<WonderBox.Models.Users>
@{
    ViewBag.Title = "AdminView";
}

<h2>AdminView</h2>


@{
    var totalMonthSub = Model.Sum(a => a.MonthlySubscription);
    var totalYearSub = Model.Sum(b => b.YearlySubscription);
    var totalSubRevenue = Model.Sum(c => c.AmountOwed);
    var totalSubscribers = Model.Sum(d => d.MonthlySubscription + d.YearlySubscription);
    decimal totalMonthlyRevenue = Math.Round(Model.Sum(e => e.TotalMonthlyRevenuIncoming ), 2);
    var totalReg = Model.Sum(f => f.TotalRegistered);
    var AverageAge = Model.Average(g => g.Age);
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zipcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MonthlySubscription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearlySubscription)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountOwed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonthlySubscription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearlySubscription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>

        </tr>
    }
    <tr>
        <th>
            Total Registered Users
        </th>
        <th>
            Average Age
        </th>
        <th>
            Total Subscriptions
        </th>
        <th>
            Total Monthly Subscriptions
        </th>
        <th>
            Total Yearly Subscritptions
        </th>
        <th>
            Total Revenue
        </th>
        <th>
            Total Monthly Incoming
        </th>
        @*<th>
            Total Male Users
        </th>
        <th>
            Total Female Users
        </th>*@
    </tr>
    <tr>
        <td>
            @totalReg
        </td>
        <td>
            @AverageAge
        </td>
        <td>
            @totalSubscribers
        </td>
        <td>
            @totalMonthSub
        </td>
        <td>
            @totalYearSub
        </td>
        <td>
            @totalSubRevenue
        </td>
        <td>
            @totalMonthlyRevenue
        </td>
        @*@foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.TotalMale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalFemale)
            </td>
        }*@
    </tr>


</table>

WonderBox/Views/Users/BuyMonthly.cshtml

@{
    ViewBag.Title = "BuyMonthly";
}

<h2>Thank You for purchasing a Mystery Box!</h2>

<h2> For optimal savings please look into purchasing our 1 year subscrpition saving you $60!</h2>


<p> Please check your profile for amount owed.</p>

<p><a onclick='window.location="@Url.Action("Index","Surveys")";' class="btn btn-primary btn-lg"> Take Survey&raquo;</a></p>
<p>Taking the survey will create the contents of your box.  If Survey is skipped the contents will be random.</p>


WonderBox/Views/Users/BuyYearly.cshtml
@model IEnumerable<WonderBox.Models.Users>
@{
    ViewBag.Title = "BuyYearly";
}

<h2>Thank You for purchasing your 1 year subscription!!</h2>

<p> Please Check your Profile for your amount owed.</p>

<p><a onclick='window.location="@Url.Action("Index","Surveys")";' class="btn btn-primary btn-lg">Take Survey &raquo;</a></p>
<p>Taking the survey will create the contents of your box.  If Survey is skipped the contents will be random.</p>

WonderBox/Views/Users/Create.cshtml
@model WonderBox.Models.Users

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Users</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Complete Registration" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WonderBox/Views/Users/Delete.cshtml
@model WonderBox.Models.Users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WonderBox/Views/Users/Details.cshtml
@model WonderBox.Models.Users

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WonderBox/Views/Users/Index.cshtml
@model IEnumerable<WonderBox.Models.Users>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zipcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MonthlySubscription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearlySubscription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) { 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zipcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AmountOwed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MonthlySubscription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearlySubscription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<div>
    <button type="submit" onclick="window.location.href ='@Url.Action("BuyMonthly")'" style="background-color:cornflowerblue">Buy A Box</button>
</div>
<div>
    <button type="submit" onclick="window.location.href ='@Url.Action("BuyYearly")'" style="background-color:cornflowerblue">Buy Yearly Subscription</button>
</div>

